version: '2.13'

services:
  rest-api:
    restart: always
    build: ./
    command: ./rest-api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5436:5432

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./schema:/database
    command:
      [ "-path", "/database", "-database",  "postgres://postgres:qwerty@db:5432/postgres?sslmode=disable", "up" ]